### ISSUE TITLE
Wrong clues?

### ISSUE THREAD

**Issue by MrVestacus** [geheur/watson-master-clue-tracker#1] opened 2021-07-07 16:15 UTC
The plugin says I need to give easy and medium clues to Watson, but Watson says I need to give him an elite clue as well.

**Comment by geheur** [comment] 2021-07-07 16:20
Does the plugin still say that you only need to give him easy + medium after you checked with watson, or did checking with watson fix the issue?

Also, did you ever hand him clues when not playing on runelite? The plugin only works when it sees you handing/receiving a clue to/from watson.

**Comment by geheur** [comment] 2021-07-07 18:57
This was caused by a line break in the middle of "elite clue".
Fixed in 1.0.2

**Closed by geheur** 2021-07-07 18:57 UTC
